baseurl: /
title: THAIS BARACAT
theme: hugo-creative-portfolio-theme
languageCode: en-us
disqusShortname: ''
googleAnalytics: ''
params:
  copyright: '&copy;2022 Thais Baracat'
  description: Fun data analytics
  email: mbaracatt@gmail.com
  navlinks:
    - home: yes
      name: Home
      url: about/
    - name: Engineering
      url: post/
    - name: Arts
      url: arts/
    - name: Argumentative
      url: arg/
    - name: CV
      url: vitae/
    - name: Contact
      url: contact/
  sidebarAbout:
    - I am an engineer interested in data analysis and data science. In my free time, I love to be involved with arts.
    - Currently based in SÃ£o Paulo, Brazil.
  social:
    email: mbaracatt@gmail.com
    github: https://github.com/mbaracatt
    instagram: https://www.instagram.com/thaisbaracat/
    linkedin: https://www.linkedin.com/in/thais-malta-baracat-2584a4127/
  style: blue
  

markup:
  goldmark:
    renderer:
      unsafe: true
